[package]
name = "yaui"
version = "0.1.0"
edition = "2021"
description = "Yet Another Injector for Unix/Android/Android Emulator i686/x64/arm/aarch64"
repository = "https://github.com/ohchase/yaui"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "yaui"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["clap", "tracing-subscriber", "sysinfo"]

[dependencies]
clap = { version = "4.2.7", features = ["derive"], optional = true }
tracing-subscriber = { version = "0.3.17", optional = true }
sysinfo = { version = "0.29.0", optional = true }

ptrace-do = { git = "https://github.com/ohchase/ptrace-do" }
thiserror = "1.0.40"
tracing = "0.1.37"
libc = "0.2.143"
proc-maps = "0.3.1"

