[package]
name = "yaui"
version = "0.2.2"
edition = "2021"
description = "Yet Another Unix Injector with support for Android/Android Emulator i686/x64/arm/aarch64"
repository = "https://github.com/ohchase/yaui"
homepage = "https://github.com/ohchase/yaui/"
documentation = "https://docs.rs/yaui"
readme = "README.md"
license = "MIT"

[[bin]]
name = "yaui"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["clap", "tracing-subscriber", "anyhow"]

[dependencies]
clap = { version = "4.5", features = ["derive"], optional = true }
tracing-subscriber = { version = "0.3", optional = true }
anyhow = { version = "1.0", optional = true }

libc = "0.2"
ptrace-do = "0.2"
tracing = "0.1"
thiserror = "1.0"
lddtree = "0.5"
