name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ aarch64-linux-android, x86_64-linux-android, aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, i686-unknown-linux-gnu, arm-unknown-linux-gnueabi, x86_64-unknown-linux-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
          
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build target
        run: cross build --release --target ${{ matrix.target }}

      - name: Verify build output
        shell: bash
        run: |
          ls -la target/${{ matrix.target }}/release/
          file target/${{ matrix.target }}/release/yaui

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../yaui-${{ matrix.target }}.tar.gz yaui
          cd -
          ls -la yaui-${{ matrix.target }}.tar.gz
          
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
            files: yaui-${{ matrix.target }}.tar.gz
            draft: false
            prerelease: false
            generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
