name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, i686-unknown-linux-gnu, arm-unknown-linux-gnueabi, x86_64-unknown-linux-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../yaui-${{ matrix.target }}.tar.gz yaui
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
            files: 'yaui*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
